# Generated by Django 4.2.6 on 2024-01-09 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('video_url', models.URLField(null=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
